apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minikube-hostpath
  resources:
    requests:
      storage: 5Gi